[package]
name = "mudbase"
version = "0.1.0"
edition = "2021"
authors = ["Caleb Rutland <caleb@thedevious.dev>"]
description = "A library to help make developing MUDs in Rust a breeze"
repository = "https://github.com/DrVonDevious/mudbase"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
